import { Inter } from "next/font/google";
import { Crimson_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const crimson = Crimson_Pro({ subsets: ["latin"] });

export const metadata = {
  title: "World Cup Legacies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={crimson.inter}>{children}</body>
    </html>
  );
}
